# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a851f2b7a478761792ab00559f45cace76763c539df6ee94fb5ba97a7386a47d592d1b4769a86235f13ec343125a032cd9ade5a0542eabfcc943edc240bfc8dc

test:
  secret_key_base: 28e3bea34571cb2a81a67de08f4472807780c46c39ec8703c532545e6a7ce640e31b3095a987c33696c73e22f3f70b1059083907697a71fd406e2e8013665e93

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
